config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/user_signup', to: 'users#new'
  post '/user_signup', to: 'users#create'
  get '/employer_signup', to: 'employers#new'
  post '/employer_signup', to: 'employers#create'
  post '/sign_user_up', to: 'jobs#add_or_remove_from_job'
  get '/jobs/sort_by_rate', to: 'jobs#sort_by_rate'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  patch '/bid_update', to: 'jobs_users#update'

  resources :users, only: [:new, :create, :show]
  resources :employers do
    resources :jobs, only: [:new, :show, :edit, :create, :destroy]
  end
  resources :users do
    resources :jobs, only: [:update, :show, :add_or_remove_from_job]
  end
  resources :employers, only: [:new, :create]
  resources :jobs_users
  resources :jobs
  resources :tools, only: [:index, :show, :update]
end

app/models/tool.rb
class Tool < ApplicationRecord
    has_and_belongs_to_many :users

    
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

    def index
        @tools = Tool.all
    end

    def update
        tool = current_tool
        if tool.users.include?(current_user)
            tool.users.delete(current_user)
            current_user.tools.delete(current_tool)
        else
            tool.users << current_user
            current_user.tools << tool
            tool.save
            current_user.save
        end
        redirect_to tools_path
    end

    private

    def current_tool
        @tool = Tool.find_by(id: params[:id])
    end


end

app/helpers/tool_helper.rb
module ToolHelper

    def current_tool
        @tool = Tool.find_by(id: params[:id])
    end

    def tool_owned?(tool)
        current_user.tools.include?(tool)
    end
end

app/views/tools/_tool.html.erb
<p><%= link_to(tool.category, tool_path(tool.id) ) if tool_owned?(tool) %></p>

app/views/tools/_tools.html.erb
<p><%= link_to(tools.category, tool_path(tools.id) ) if !tool_owned?(tools) %></p>

app/views/tools/index.html.erb
<h4>Your Toolbox:</h4>

<%= render partial: "tool", collection: @tools %>

<h4>Add Other Tools:</h4>

<%= render partial: "tools", collection: @tools %>

app/views/tools/show.html.erb
<h2><%= current_tool.category %></h2>

<p><%= current_tool.description %></p>

<%= button_to 'Add/Remove from Toolbox', {:controller => "tools", :action => "update", :tool_id => params[:id]} , :method=>:put, class:"btn btn-info" %><br>