config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/user_signup', to: 'users#new'
  post '/user_signup', to: 'users#create'
  get '/employer_signup', to: 'employers#new'
  post '/employer_signup', to: 'employers#create'
  post '/sign_user_up', to: 'jobs#add_or_remove_from_job'
  get '/jobs/sort_by_rate', to: 'jobs#sort_by_rate'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  patch '/bid_update', to: 'jobs_users#update'

  resources :users, only: [:new, :create, :show]
  resources :employers do
    resources :jobs, only: [:new, :show, :edit, :create, :destroy]
  end
  resources :users do
    resources :jobs, only: [:update, :show, :add_or_remove_from_job]
  end
  resources :employers, only: [:new, :create]
  resources :jobs_users
  resources :jobs
  resources :tools, only: [:index, :show, :update]
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :jobs_users
    has_many :users, through: :jobs_users
    belongs_to :employer

    validates :address, presence: true
    validates :category, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :rate, presence: true

    

    def self.order_by_rate
        order(rate: :desc)
    end

    def display_link_info
        self.employer.company + " - " + self.category + " - " + "$" + self.rate.to_s + "0/hr"
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
        @jobs = Job.order(:category)
    end

    def new
        if params[:employer_id] && !Employer.exists?(params[:employer_id])
            redirect_to jobs_path, alert: "Employer not found."
        else
            @job = Job.new(employer_id: params[:employer_id])
            render :new
        end
    end

    def create
        @job = Job.new(jobs_params)
        @job.employer = current_user
        if @job.valid?
            @job.save
            redirect_to employer_job_path(current_user, @job)
        else
            render :new
        end
    end

    def edit
        if user_posted?
            @job = Job.find_by(id: params[:id])
            render :edit
        else
            redirect_to user_path(current_user)
        end
    end

    def add_or_remove_from_job
        job = Job.find_by(id: params[:job_id])
        
        if job.users.include?(current_user)
            job.users.each do |user|
                if user == current_user
                    job.users.delete(current_user)
                end
            end
            job.save            
            redirect_to job_path(job)

        elsif !job.users.include?(current_user)
            job.users << current_user
            job.save
            current_user.save
            redirect_to user_job_path(current_user, job)
        end
                    

    end

    def show
        if params[:employer_id]
            employer = Employer.find_by(id: params[:employer_id])
            if employer.nil? || employer != current_user || current_job.nil?
                redirect_to employer_path(current_user)
            else
                @job = employer.jobs.find_by(id: params[:id])
                redirect_to employer_jobs_path(employer) if @job.nil?
            end
        elsif
            @job = Job.find_by(id: params[:id])
        end
    end

    def sort_by_rate
        @jobs = Job.order_by_rate
        render :index
    end

    def update
        @job = Job.find(params[:id])
        if @job.valid?
            @job.update(jobs_params)
            redirect_to employer_path(current_user)
        else
            render :edit 
        end
    end

    def destroy
        if current_job.employer == current_user
            current_job.delete
        end
        redirect_to jobs_path
    end

    private

    def current_job
        @job = Job.find_by(id: params[:id])
    end

    def jobs_params
        params.require(:job).permit(:category, :start_date, :end_date, :rate, :requirements, :user_id, :employer_id, :address)
    end

    
end

app/helpers/job_helper.rb
module JobHelper

    def current_job
        if params[:employer_id]
            @job = Job.find_by(id: params[:employer_id])
        else
            @job = Job.find_by(id: params[:id])
        end
    end

    def current_user?(params)
        current_user.id == params[:user_id].to_i
    end

    def render_poster
        if user_posted?
            content_tag(:h2, "You posted this job")
        end
    end

    def render_sign_up_button
        if current_job.user_id == nil
            content_tag(:p, "Sign Up")
        elsif current_job.user_id == current_user.id
            content_tag(:p, "Signed Up")
        end
    end

    def all_jobs
        @jobs = Job.all
    end

    def date_format(date)
        date.strftime("%A, %b %e, at %l:%M %p")
    end
    
    def job_user?
        !!params[:user_id]
    end

    def job_bid_by_worker(worker)
        worker.jobs_users.find_by(job_id: params[:id]).rate.to_i
    end

    def job_bid
        if worker?
            if current_user.jobs_users.find_by(job_id: params[:id]).nil?
                nil
            else
                current_user.jobs_users.find_by(job_id: params[:id]).rate
            end
        end
    end

    def render_job_bid
        if job_bid
            content_tag(:p, "Your Bid: $#{job_bid}.00/hr")
        else
            nil
        end
    end
end

app/views/jobs/_job.html.erb
<p><%= link_to(job.display_link_info, job_path(job.id)) %></p>

app/views/jobs/_job_form.html.erb
<%= render partial: "layouts/error", locals: {object: @job}  %>

<%= form_for(@job) do |f| %>
    <%= f.label "Address:", class: "lead" %><br>
    <%= f.text_field :address %><br><br>
    <%= f.label "Category: ", class: "lead" %>
    <%= f.select :category, ["Construction", "Landscaping", "IT", "Computer Repair", "Catering"] %><br><br>
    <%= f.label "Start Date: ", class: "lead" %><br><br>
    <%= f.date_select :start_date %><br><br>
    <%= f.time_select :start_date, :ignore_date => true %><br><br>
    <%= f.label "End Date:", class: "lead" %><br><br>
    <%= f.date_select :end_date %><br><br>
    <%= f.time_select :end_date, :ignore_date => true %><br><br>
    <%= f.label "Desired Rate:", class: "lead" %><br><br>
    <%= f.number_field :rate %><br><br>

    <%= f.submit %><br><br>
<% end %>

app/views/jobs/edit.html.erb
<h3>Edit Job:</h3>
<%= render partial: "job_form", locals: {object: @job}%>

<%= button_to "Delete Job", job_path(@job), method: 'delete' %><br>

app/views/jobs/index.html.erb
<h3>Availiable Jobs:</h3>
<%= link_to "Sort by Rate", '/jobs/sort_by_rate' %><br><br>
<%= render partial: "job", collection: @jobs %>

app/views/jobs/new.html.erb
<h3>Post New Job</h3>

<%= render partial: "job_form", locals: {job: @job} %>

app/views/jobs/show.html.erb
<p>Category: <%= @job.category %></p>
<p>Employer: <%= @job.employer.company %></p>
<p>Address: <%= @job.address %></p
<p>Start: <%= date_format(@job.start_date) %></p>
<p>End: <%= date_format(@job.end_date) %></p>
<p>Desired Rate: $<%= @job.rate %>0/hr</p>
<%= render_job_bid %>
<% if current_user?(params) %>
    <%= form_for(current_user.jobs_users.find_by(job_id: params[:id]), url: "/bid_update") do |f|%>
        <%= hidden_field_tag(:user_id, params[:user_id]) %>
        <%= hidden_field_tag(:job_id, params[:id]) %>
        <%= f.label "Bid: " %>
        <%= f.number_field :rate %>

        <%= f.submit "Place Bid" %><br><br>
    <% end %>
<% end %>
<%= (button_to 'Add/Remove Job', {:controller => "jobs", :action => "add_or_remove_from_job", :job_id => params[:id]} , :method=>:post) if worker?%><br>

<% if @job.users.any? %>
    <p>Current Crew:</p>
    <ul>
    <% @job.users.each do |user| %>
        <li><%= user_full_name(user) %><%= " - Bid: $#{job_bid_by_worker(user)}.00/hr" if employer? %></li>
    <% end %>
    </ul>
<% end %>

<%= link_to 'Edit Job', edit_job_path(@job) if user_created_job?(@job)%><br><br>