config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/user_signup', to: 'users#new'
  post '/user_signup', to: 'users#create'
  get '/employer_signup', to: 'employers#new'
  post '/employer_signup', to: 'employers#create'
  post '/sign_user_up', to: 'jobs#add_or_remove_from_job'
  get '/jobs/sort_by_rate', to: 'jobs#sort_by_rate'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  patch '/bid_update', to: 'jobs_users#update'

  resources :users, only: [:new, :create, :show]
  resources :employers do
    resources :jobs, only: [:new, :show, :edit, :create, :destroy]
  end
  resources :users do
    resources :jobs, only: [:update, :show, :add_or_remove_from_job]
  end
  resources :employers, only: [:new, :create]
  resources :jobs_users
  resources :jobs
  resources :tools, only: [:index, :show, :update]
end

app/models/employer.rb
class Employer < ApplicationRecord
    has_many :jobs
    # has_many :users, through: :jobs
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true
    validates :company, presence: true
    validates :password, length: {in: 3..20}
    has_secure_password
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
    layout :resolve_layout
    
    def index
        redirect_to employer_path(current_user)
    end

    def new
        @employer = Employer.new
    end

    def create
        @employer = Employer.new(employer_params)
        if @employer.valid?
            @employer.save
            session[:employer_id] = @employer.id
            redirect_to employer_path(@employer)
        else
            render :new
        end
    end

    def show
        if params[:id].to_i != session[:employer_id]
            redirect_to employer_path(current_user)
        else
            employer = Employer.find_by(id: params[:id])
            @job = employer.jobs.find_by(id: params[:id])
            render :show
        end
    end

    def update
    end

    def logout
        session.clear[:Employer_id]
        redirect :index
    end

    def destroy
    end

    private

    def resolve_layout
        case action_name
        when "new", "create"
            "sessions"
        else
            "application"
        end
    end

    def employer_params
        params.require(:employer).permit(:first_name, :last_name, :username, :email, :password, :bio, :company)
    end
end

app/helpers/employer_helper.rb
module EmployerHelper

    def current_employer
        @employer = Employer.find_by(id: session[:employer_id])
    end

    def employer?
        !!session[:employer_id]
    end

    def user_created_job?(job)
        job.employer.id == session[:employer_id]
    end

    # def employer_full_name(employer)
    #     "#{employer.first_name} #{employer.last_name}"
    # end
end

app/views/employers/new.html.erb
<%= link_to "Back", '/' %>

<h2>Create a New Employer Account</h2><br>
<%= render partial: "layouts/error", locals: {object: @employer}  %>

<%= form_for(@employer, url:'/employer_signup')do |f|%>
    <%= f.label :first_name, class: "lead" %>
    <%= f.text_field :first_name %><br><br>
    <%= f.label :last_name, class: "lead" %>
    <%= f.text_field :last_name %><br><br>
    <%= f.label :username, class: "lead" %>
    <%= f.text_field :username %><br><br>
    <%= f.label :email, class: "lead" %>
    <%= f.email_field :email %><br><br>
    <%= f.label :password, class: "lead" %>
    <%= f.password_field :password %><br><br>
    <%= f.label :company, class: "lead" %>
    <%= f.text_field :company %><br><br>
    <%= f.label :bio, class: "lead" %>
    <%= f.text_field :bio %><br><br>
    <%= f.submit "Sign Up"%>
<% end %>

app/views/employers/show.html.erb
<h3>Your Jobs: </h3>
<% all_jobs.each do |job| %>
    <p><%= link_to(job.display_link_info, employer_job_path(current_user, job)) if job.employer == current_user %></p>
<%end%>