config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/user_signup', to: 'users#new'
  post '/user_signup', to: 'users#create'
  get '/employer_signup', to: 'employers#new'
  post '/employer_signup', to: 'employers#create'
  post '/sign_user_up', to: 'jobs#add_or_remove_from_job'
  get '/jobs/sort_by_rate', to: 'jobs#sort_by_rate'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  patch '/bid_update', to: 'jobs_users#update'

  resources :users, only: [:new, :create, :show]
  resources :employers do
    resources :jobs, only: [:new, :show, :edit, :create, :destroy]
  end
  resources :users do
    resources :jobs, only: [:update, :show, :add_or_remove_from_job]
  end
  resources :employers, only: [:new, :create]
  resources :jobs_users
  resources :jobs
  resources :tools, only: [:index, :show, :update]
end

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
        <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
    </div>
<% end %> 

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Hustle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  </head>
  
  <body>
    <div class="container-fluid">
      <div class="navbar-text navbar-fixed-top mb-2"><%= "Signed in as " + show_logged_in if logged_in? %></div><br>
      
      <ul class="nav nav-tabs">
        <li class="pr-1"><%= link_to "Home", employer_path(current_user.id) if employer? %></li>
        <li class="pr-1"><%= link_to "Home", user_path(current_user.id) if worker? %></li><li>|</li>
        <li class="pl-1 pr-1"><%= link_to "Jobs", jobs_path if logged_in? %></li><li>|</li>
        <li class="pl-1"><%= link_to "Post a Job", new_employer_job_path(current_user) if employer? %></li>
        <li><%= link_to "Toolbox", tools_path if worker? %></li>
      </ul>
          
      <%= yield %>

      <ul class="nav navbar-nav navbar-bottom">
        <li><%= button_to "Logout", logout_path, method: 'delete', class: "btn btn-primary" if logged_in?%></li>
      </ul>
      
    </div>
  </body>
</html>

app/views/layouts/sessions.html.erb
  
<!DOCTYPE html>
<html>
  <head>
    <title>Hustle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <div class="container-fluid">
    <body>  
        <%= yield %>
    </body>
  </div>
</html>